/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BriefRouteImport } from './routes/brief'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as RuntimeRouteImport } from './routes/runtime'
import { Route as PlansIndexRouteImport } from './routes/plans.index'
import { Route as PlansVersionRouteImport } from './routes/plans.$version'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefRoute = BriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeRoute = RuntimeRouteImport.update({
  id: '/runtime',
  path: '/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansVersionRoute = PlansVersionRouteImport.update({
  id: '/plans/$version',
  path: '/plans/$version',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brief': typeof BriefRoute
  '/library': typeof LibraryRoute
  '/runtime': typeof RuntimeRoute
  '/plans/$version': typeof PlansVersionRoute
  '/plans/': typeof PlansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brief': typeof BriefRoute
  '/library': typeof LibraryRoute
  '/runtime': typeof RuntimeRoute
  '/plans/$version': typeof PlansVersionRoute
  '/plans': typeof PlansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brief': typeof BriefRoute
  '/library': typeof LibraryRoute
  '/runtime': typeof RuntimeRoute
  '/plans/$version': typeof PlansVersionRoute
  '/plans/': typeof PlansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/brief' | '/library' | '/runtime' | '/plans/$version' | '/plans/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/brief' | '/library' | '/runtime' | '/plans/$version' | '/plans'
  id:
    | '__root__'
    | '/'
    | '/brief'
    | '/library'
    | '/runtime'
    | '/plans/$version'
    | '/plans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BriefRoute: typeof BriefRoute
  LibraryRoute: typeof LibraryRoute
  RuntimeRoute: typeof RuntimeRoute
  PlansVersionRoute: typeof PlansVersionRoute
  PlansIndexRoute: typeof PlansIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief': {
      id: '/brief'
      path: '/brief'
      fullPath: '/brief'
      preLoaderRoute: typeof BriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime': {
      id: '/runtime'
      path: '/runtime'
      fullPath: '/runtime'
      preLoaderRoute: typeof RuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/': {
      id: '/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$version': {
      id: '/plans/$version'
      path: '/plans/$version'
      fullPath: '/plans/$version'
      preLoaderRoute: typeof PlansVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BriefRoute: BriefRoute,
  LibraryRoute: LibraryRoute,
  RuntimeRoute: RuntimeRoute,
  PlansVersionRoute: PlansVersionRoute,
  PlansIndexRoute: PlansIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
